on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: read

jobs:
  release-on-push:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - run: yarn version --patch

      # - uses: rymndhng/release-on-push-action@master
      #   with:
      #     bump_version_scheme: minor
      #     release_body: "When set, adds extra text to body!"
