on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: read

jobs:
  release-on-push:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - run: |
          git config --global user.email "yuseunghwan94@gmail.com"
          git config --global user.name "mechaniccoder"
          yarn version --patch

          git commit -m "Update version
          git push

      # - uses: rymndhng/release-on-push-action@master
      #   with:
      #     bump_version_scheme: minor
      #     release_body: "When set, adds extra text to body!"
