on:
  pull_request:
    types:
      - closed
    branches:
      - main

permissions:
  contents: write
  pull-requests: read

jobs:
  release-on-push:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - run: echo ${{ github.event }}
      - run: echo ${{ github.event.pull_request.labels[0].name }}

      # - name: checkout
      #   uses: actions/checkout@v3

      # - id: version
      #   run: |
      #     git config --global user.email "yuseunghwan94@gmail.com"
      #     git config --global user.name "mechaniccoder"
      #     yarn version --patch
      #     git push
      #     echo "version=$(node -p "require('./package.json').version")" >> "$GITHUB_OUTPUT"

      # - name: Using new version
      #   run: echo ${{ steps.version.outputs.version }}

      # - id: release
      #   uses: rymndhng/release-on-push-action@master
      #   with:
      #     bump_version_scheme: minor
      #     release_body: "When set, adds extra text to body!"

      # - run: echo ${{ steps.release.outputs.body }}
