on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: read

jobs:
  release-on-push:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - id: version
        run: |
          git config --global user.email "yuseunghwan94@gmail.com"
          git config --global user.name "mechaniccoder"
          yarn version --patch
          git push
          echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT"

      - name: Using new version
        run: echo ${{ steps.version.outputs.version }}

      # - uses: rymndhng/release-on-push-action@master
      #   with:
      #     bump_version_scheme: minor
      #     release_body: "When set, adds extra text to body!"
